var product_json=[

    // Air Optix
    {"id":"a01",
    "brandId":"a",
    "name":"AMETHYST PRESCRIPTION",
    "pic":"images\\Airoptix\\1\\1.jpg","pic2":"images\\Airoptix\\1\\2.jpg",
    "price":16,
    "detail":"Discover your new favourite eye color with these gorgeous Amethyst Contact Lenses from Air Optix. Available here in a variety of corrective strengths.",
    "detailVi":"Khám phá màu mắt yêu thích mới của bạn với Kính áp tròng thạch anh tím tuyệt đẹp này của Air Optix. Có sẵn ở đây trong một loạt các cường độ.",
    "color":"Purple","colorVi":"Tím",
    "doc":"images\\Airoptix\\1\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    {"id":"a02",
    "brandId":"a",
    "name":"GEMSTONE GREEN",
    "pic":"images\\Airoptix\\2\\1.jpg","pic2":"images\\Airoptix\\2\\2.jpg",
    "price":17,
    "detail":"Transform your eye color with Air Optix Colors Gemstone Green for a vibrant eye color that offers bold coverage for natural looks.",
    "detailVi":"Biến đổi màu mắt của bạn với Air Optix Colors Gemstone Green để có màu mắt rực rỡ, mang lại độ che phủ đậm cho vẻ ngoài tự nhiên.",
    "color":"Green","colorVi":"Xanh lá",
    "doc":"images\\Airoptix\\2\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    {"id":"a03",
    "brandId":"a",
    "name":"HONEY PRESCRIPTION",
    "pic":"images\\Airoptix\\3\\1.jpg","pic2":"images\\Airoptix\\3\\2.jpg",
    "price":18,
    "detail":"The Air Optix Colors Honey Prescription Contact Lenses in 30 Day have a golden brown tone that is sure to enhance your eye color. These natural contact lenses give you the chance to try a new everyday or special occasion look.",
    "detailVi":"Kính áp tròng theo toa của Air Optix Colors Honey trong 30 ngày có tông màu nâu vàng, chắc chắn sẽ tôn lên màu mắt của bạn. Những chiếc kính áp tròng tự nhiên này mang đến cho bạn cơ hội thử một kiểu dáng mới hàng ngày hoặc vào dịp đặc biệt.",
    "color":"Brown","colorVi":"Nâu",
    "doc":"images\\Airoptix\\3\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    {"id":"a04",
    "brandId":"a",
    "name":"GRAY PRESCRIPTION",
    "pic":"images\\Airoptix\\4\\1.jpg","pic2":"images\\Airoptix\\4\\2.jpg",
    "price":16,
    "detail":"The Air Optix Colors Gray Prescription  Contact Lenses in 30 Day offer a vibrant gray eye color coupled with clear vision and a monthly reusable style.",
    "detailVi":"Kính áp tròng theo toa của Air Optix Colors Grey trong 30 ngày cung cấp màu mắt xám sống động cùng với tầm nhìn rõ ràng và kiểu dáng có thể tái sử dụng hàng tháng.",
    "color":"Gray","colorVi":"Xám",
    "doc":"images\\Airoptix\\4\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    {"id":"a05",
    "brandId":"a",
    "name":"TRUE SAPPHIRE PRESCRIPTION",
    "pic":"images\\Airoptix\\5\\1.jpg","pic2":"images\\Airoptix\\5\\2.jpg",
    "price":17,
    "detail":"The Air Optix Colors True Sapphire Prescription  Contact Lenses in 30 Day. These natural blue contact lenses will help you enjoy a new eye color and clear vision.",
    "detailVi":"Kính áp tròng theo toa của Air Optix Colors True Sapphire trong 30 ngày. Những chiếc kính áp tròng màu xanh lam tự nhiên này sẽ giúp bạn có màu mắt mới và tầm nhìn rõ ràng.",
    "color":"Blue","colorVi":"Xanh",
    "doc":"images\\Airoptix\\5\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    {"id":"a06",
    "brandId":"a",
    "name":"AMETHYST PRESCRIPTION",
    "pic":"images\\Airoptix\\1\\1.jpg","pic2":"images\\Airoptix\\1\\2.jpg",
    "price":19,
    "detail":"Discover your new favourite eye color with these gorgeous Amethyst Contact Lenses from Air Optix. Available here in a variety of corrective strengths.",
    "detailVi":"Khám phá màu mắt yêu thích mới của bạn với Kính áp tròng thạch anh tím tuyệt đẹp này của Air Optix. Có sẵn ở đây trong một loạt các cường độ.",
    "color":"Purple","colorVi":"Tím",
    "doc":"images\\Airoptix\\1\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    {"id":"a07",
    "brandId":"a",
    "name":"GEMSTONE GREEN",
    "pic":"images\\Airoptix\\2\\1.jpg","pic2":"images\\Airoptix\\2\\2.jpg",
    "price":18,
    "detail":"Transform your eye color with Air Optix Colors Gemstone Green for a vibrant eye color that offers bold coverage for natural looks.",
    "detailVi":"Biến đổi màu mắt của bạn với Air Optix Colors Gemstone Green để có màu mắt rực rỡ, mang lại độ che phủ đậm cho vẻ ngoài tự nhiên.",
    "color":"Green","colorVi":"Xanh lá",
    "doc":"images\\Airoptix\\2\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    {"id":"a08",
    "brandId":"a",
    "name":"HONEY PRESCRIPTION",
    "pic":"images\\Airoptix\\3\\1.jpg","pic2":"images\\Airoptix\\3\\2.jpg",
    "price":17,
    "detail":"The Air Optix Colors Honey Prescription  Contact Lenses in 30 Day have a golden brown tone that is sure to enhance your eye color. These natural contact lenses give you the chance to try a new everyday or special occasion look.",
    "detailVi":"Kính áp tròng theo toa của Air Optix Colors Honey trong 30 ngày có tông màu nâu vàng, chắc chắn sẽ tôn lên màu mắt của bạn. Những chiếc kính áp tròng tự nhiên này mang đến cho bạn cơ hội thử một kiểu dáng mới hàng ngày hoặc vào dịp đặc biệt.",
    "color":"Brown","colorVi":"Nâu",
    "doc":"images\\Airoptix\\3\\CONTACT-LENSES.docx",
    "brand":"Air Optix",
    "manufacturer":"AirOptix",
    "style":"Natural","styleVi":"Thời trang",
    "duration":30,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"33%",
    "made_from":"Lotrafilcon B",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"
    },

    // Chromaview
    {"id":"c01",
    "brandId":"c",
    "name":"VIOLET GALAXY ",
    "pic":"images\\Chromaview\\1\\1.jpg","pic2":"images\\Chromaview\\1\\2.jpg",
    "price":16,
    "detail":"Get a bright and beautiful look that's out of this world with the Violet Galaxy  Contact Lenses in 90 Day! ",
    "detailVi":"Có được vẻ ngoài tươi sáng và xinh đẹp như ngoài thế giới này với Kính áp tròng Violet Galaxy trong 90 ngày! ",
    "color":"Purple","colorVi":"Tím",
    "doc":"images\\Chromaview\\1\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"c02",
    "brandId":"c",
    "name":"BLUE SHIVA  PRESCRIPTION",
    "pic":"images\\Chromaview\\2\\1.jpg","pic2":"images\\Chromaview\\2\\2.jpg",
    "price":17,
    "detail":"Give your cosplay a bright icy shade with the Blue Shiva  Prescription Contact Lenses in 90 Day",
    "detailVi":"Mang đến cho bộ cosplay của bạn một bóng râm băng giá tươi sáng với Kính áp tròng Kê đơn Blue Shiva trong 90 ngày",
    "color":"Blue","colorVi":"Xanh",
    "doc":"images\\Chromaview\\2\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"c03",
    "brandId":"c",
    "name":"WHITE OUT  PRESCRIPTION",
    "pic":"images\\Chromaview\\3\\1.jpg","pic2":"images\\Chromaview\\3\\2.jpg",
    "price":18,
    "detail":"Take your zombie costume to new heights with the spooky 90 Day White Out  Prescription Contact Lenses!",
    "detailVi":"Đưa trang phục zombie của bạn lên một tầm cao mới với Kính áp tròng 90 Ngày White Out ma quái!",
    "color":"Floralwhite","colorVi":"Trắng",
    "doc":"images\\Chromaview\\3\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"c04",
    "brandId":"c",
    "name":"BLACK MESH",
    "pic":"images\\Chromaview\\4\\1.jpg","pic2":"images\\Chromaview\\4\\2.jpg",
    "price":16,
    "detail":"Totally transform your eyes with these Black Mesh  Contact Lenses - perfect for scary Halloween costumes.",
    "detailVi":"Biến đổi hoàn toàn đôi mắt của bạn với Kính áp tròng Lưới đen này - hoàn hảo cho những bộ trang phục Halloween đáng sợ.",
    "color":"Black","colorVi":"Đen",
    "doc":"images\\Chromaview\\4\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"c05",
    "brandId":"c",
    "name":"YELLOW AVATAR ",
    "pic":"images\\Chromaview\\5\\1.jpg","pic2":"images\\Chromaview\\5\\2.jpg",
    "price":17,
    "detail":"Become one of the Na'vi in the Avatar 30 Day  Contact Lenses; perfect for creating an authentic Avatar Cosplay or costume party look!",
    "detailVi":"Trở thành một trong những Na'vi trong Kính áp tròng 30 ngày Thế thần; hoàn hảo để tạo ra một Cosplay Avatar đích thực hoặc giao diện trang phục trong bữa tiệc!",
    "color":"Yellow","colorVi":"Vàng",
    "doc":"images\\Chromaview\\5\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},

    {"id":"c06",
    "brandId":"c",
    "name":"VIOLET GALAXY ",
    "pic":"images\\Chromaview\\1\\1.jpg","pic2":"images\\Chromaview\\1\\2.jpg",
    "price":19,
    "detail":"Get a bright and beautiful look that's out of this world with the Violet Galaxy  Contact Lenses in 90 Day! ",
    "detailVi":"Có được vẻ ngoài tươi sáng và xinh đẹp như ngoài thế giới này với Kính áp tròng Violet Galaxy trong 90 ngày!",
    "color":"Purple","colorVi":"Tím",
    "doc":"images\\Chromaview\\1\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"c07",
    "brandId":"c",
    "name":"BLUE SHIVA  PRESCRIPTION",
    "pic":"images\\Chromaview\\2\\1.jpg","pic2":"images\\Chromaview\\2\\2.jpg",
    "price":18,
    "detail":"Give your cosplay a bright icy shade with the Blue Shiva  Prescription Contact Lenses in 90 Day",
    "detailVi":"Mang đến cho bộ cosplay của bạn một bóng râm băng giá tươi sáng với Kính áp tròng Kê đơn Blue Shiva trong 90 ngày",
    "color":"Blue","colorVi":"Xanh",
    "doc":"images\\Chromaview\\2\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"c08",
    "brandId":"c",
    "name":"WHITE OUT  PRESCRIPTION",
    "pic":"images\\Chromaview\\3\\1.jpg","pic2":"images\\Chromaview\\3\\2.jpg",
    "price":17,
    "detail":"Take your zombie costume to new heights with the spooky 90 Day White Out  Prescription Contact Lenses!",
    "detailVi":"Đưa trang phục zombie của bạn lên một tầm cao mới với Kính áp tròng 90 Ngày White Out ma quái!",
    "color":"White","colorVi":"Trắng",
    "doc":"images\\Chromaview\\3\\CONTACT-LENSES.docx",
    "brand":"Chromaview",
    "manufacturer":"Chromaview",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polymacon",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},

    // Eyefusion
    {"id":"e01",
    "brandId":"e",
    "name":"GREEN YELLOW FUSION ",
    "pic":"images\\Eyefusion\\1\\1.jpg","pic2":"images\\Eyefusion\\1\\2.jpg",
    "price":6,
    "detail":"Get a green glow with these awesome Daily Green & Yellow Fusion  Contact Lenses; perfect for creating a mythical Cosplay!",
    "detailVi":"Nhận ánh sáng xanh với Kính áp tròng Fusion Green & Yellow hàng ngày tuyệt vời này; hoàn hảo để tạo ra một Cosplay thần thoại!",
    "color":"Green","colorVi":"Xanh lá",
    "doc":"images\\Eyefusion\\1\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"e02",
    "brandId":"e",
    "name":"RED CRAZY CLOWN ",
    "pic":"images\\Eyefusion\\2\\1.jpg","pic2":"images\\Eyefusion\\2\\2.jpg",
    "price":7,
    "detail":"Whoever says that clowns are scary is absolutely right! You are sure to look freaky in these Red Crazy Clown  Contact Lenses in Daily.",
    "detailVi":"Ai nói rằng những chú hề đáng sợ là hoàn toàn đúng! Bạn chắc chắn sẽ trông thật quái dị trong những chiếc Kính áp tròng Red Crazy Clown này hàng ngày.",
    "color":"Red","colorVi":"Đỏ",
    "doc":"images\\Eyefusion\\2\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"e03",
    "brandId":"e",
    "name":"GOLD VAMPIRE ",
    "pic":"images\\Eyefusion\\3\\1.jpg","pic2":"images\\Eyefusion\\3\\2.jpg",
    "price":8,
    "detail":"Create a scary stare with the Gold Vampire 1 Day  Contact Lenses, a must have accessory for Halloween!",
    "detailVi":"Tạo ánh nhìn đáng sợ với Kính áp tròng 1 ngày Gold Vampire, một phụ kiện phải có cho Halloween!",
    "color":"Orange","colorVi":"Cam",
    "doc":"images\\Eyefusion\\3\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"e04",
    "brandId":"e",
    "name":"GRAY BLIND ",
    "pic":"images\\Eyefusion\\4\\1.jpg","pic2":"images\\Eyefusion\\4\\2.jpg",
    "price":6,
    "detail":"Shroud your eyes in mystery with the Gray Blind Daily Contact Lenses. These horror lenses do not have a pupil hole, so please note that your vision will be obscured during wear. Perfect for ghostly Halloween makeup.",
    "detailVi":"Che mắt bạn trong bí ẩn với Kính áp tròng hàng ngày Grey Blind. Những ống kính kinh dị này không có lỗ đồng tử, vì vậy xin lưu ý rằng tầm nhìn của bạn sẽ bị che khuất trong quá trình đeo. Hoàn hảo cho trang điểm Halloween ma quái.",
    "color":"Gray","colorVi":"Xám",
    "doc":"images\\Eyefusion\\4\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"e05",
    "brandId":"e",
    "name":"DEMON ",
    "pic":"images\\Eyefusion\\5\\1.jpg","pic2":"images\\Eyefusion\\5\\2.jpg",
    "price":7,
    "detail":"Create your own monster look with the Daily  Contact Lenses in Demon, perfect for Halloween fancy dress!",
    "detailVi":"Tạo ra vẻ ngoài quái vật của riêng bạn với Kính áp tròng hàng ngày trong Demon, hoàn hảo cho trang phục lộng lẫy của Halloween!",
    "color":"Red","colorVi":"Đỏ",
    "doc":"images\\Eyefusion\\5\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},

    {"id":"e06",
    "brandId":"e",
    "name":"GREEN YELLOW FUSION ",
    "pic":"images\\Eyefusion\\1\\1.jpg","pic2":"images\\Eyefusion\\1\\2.jpg",
    "price":9,
    "detail":"Get a green glow with these awesome Daily Green & Yellow Fusion  Contact Lenses; perfect for creating a mythical Cosplay!",
    "detailVi":"Nhận ánh sáng xanh với Kính áp tròng Fusion Green & Yellow hàng ngày tuyệt vời này; hoàn hảo để tạo ra một Cosplay thần thoại!",
    "color":"Green","colorVi":"Xanh lá",
    "doc":"images\\Eyefusion\\1\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"e07",
    "brandId":"e",
    "name":"RED CRAZY CLOWN",
    "pic":"images\\Eyefusion\\2\\1.jpg","pic2":"images\\Eyefusion\\2\\2.jpg",
    "price":8,
    "detail":"Whoever says that clowns are scary is absolutely right! You are sure to look freaky in these Red Crazy Clown  Contact Lenses in Daily.",
    "detailVi":"Ai nói rằng những chú hề đáng sợ là hoàn toàn đúng! Bạn chắc chắn sẽ trông thật quái dị trong những chiếc Kính áp tròng Red Crazy Clown này hàng ngày.",
    "color":"Red","colorVi":"Đỏ",
    "doc":"images\\Eyefusion\\2\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"e08",
    "brandId":"e",
    "name":"GOLD VAMPIRE",
    "pic":"images\\Eyefusion\\3\\1.jpg","pic2":"images\\Eyefusion\\3\\2.jpg",
    "price":7,
    "detail":"Create a scary stare with the Gold Vampire 1 Day  Contact Lenses, a must have accessory for Halloween!",
    "detailVi":"Tạo ánh nhìn đáng sợ với Kính áp tròng 1 ngày Gold Vampire, một phụ kiện phải có cho Halloween!",
    "color":"Orange","colorVi":"Cam",
    "doc":"images\\Eyefusion\\3\\CONTACT-LENSES.docx",
    "brand":"Eyefusion",
    "manufacturer":"Eye fusion",
    "style":"Costume","styleVi":"Hóa trang",
    "duration":1,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"no","corrective_LenVi":"không",
    "type":"0.00 / Plano","typeVi":"0.00 / Plano",
    "diameter":14.2,
    "base_curve":8.6,
    "water_content":"38%",
    "made_from":"Polyhema",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},

    // FRESHLOOK
    {"id":"f01",
    "brandId":"f",
    "name":"COLORBLENDS GREEN PRESCRIPTION",
    "pic":"images\\Freshlook\\1\\1.jpg","pic2":"images\\Freshlook\\1\\2.jpg",
    "price":10,
    "detail":"Discover a vibrant new eye color with the Freshlook Colorblends Green  Contact Lenses in 30 Day - a natural everyday design.",
    "detailVi":"Khám phá màu mắt mới đầy sức sống với Kính áp tròng Freshlook Colorblends Green trong 30 ngày - một thiết kế tự nhiên hàng ngày.",
    "color":"Green","colorVi":"Xanh lá",
    "doc":"images\\Freshlook\\1\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"f02","brandId":"f",
    "name":"COLORBLENDS AMETHYST PRESCRIPTION ",
    "pic":"images\\Freshlook\\2\\1.jpg","pic2":"images\\Freshlook\\2\\2.jpg",
    "price":11,
    "detail":"With the Freshlook Colorblends Amethyst  Contact Lenses in 30 Day, you can enjoy a gorgeous purple tone in a natural design.",
    "detailVi":"Với Kính áp tròng thạch anh tím Freshlook Colorblends trong 30 ngày, bạn có thể tận hưởng tông màu tím tuyệt đẹp trong một thiết kế tự nhiên.",
    "color":"Purple","colorVi":"Tím",
    "doc":"images\\Freshlook\\2\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"f03","brandId":"f",
    "name":"COLORBLENDS BLUE PRESCRIPTION ",
    "pic":"images\\Freshlook\\3\\1.jpg","pic2":"images\\Freshlook\\3\\2.jpg",
    "price":12,
    "detail":"Try out a natural new eye colour with the realistic look of the Freshlook Colorblends Blue Coloured Contact Lenses in 30 Day!",
    "detailVi":"Hãy thử màu mắt mới tự nhiên với kiểu dáng thực tế của Kính áp tròng màu xanh Freshlook Colorblends trong 30 ngày!",
    "color":"Blue","colorVi":"Xanh",
    "doc":"images\\Freshlook\\3\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"f04","brandId":"f",
    "name":"COLORBLENDS HONEY PRESCRIPTION ",
    "pic":"images\\Freshlook\\4\\1.jpg","pic2":"images\\Freshlook\\4\\2.jpg",
    "price":10,
    "detail":"Introducing a new unusual natural eye color with the Freshlook Colorblends Honey  Contact Lenses in 30 Day - designed for everyday wear.",
    "detailVi":"Giới thiệu màu mắt tự nhiên mới lạ với Kính áp tròng Freshlook Colorblends Honey trong 30 ngày - được thiết kế để đeo hàng ngày.",
    "color":"Brown","colorVi":"Nâu",
    "doc":"images\\Freshlook\\4\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"f05","brandId":"f",
    "name":"COLORBLENDS STERLING GRAY PRESCRIPTION",
    "pic":"images\\Freshlook\\5\\1.jpg","pic2":"images\\Freshlook\\5\\2.jpg",
    "price":11,
    "detail":"Recreate your everyday look with the Freshlook Colorblends Sterling Gray Prescription Contact Lenses. ",
    "detailVi":"Tái tạo vẻ ngoài hàng ngày của bạn với Kính áp tròng theo toa Freshlook Colorblends Sterling Grey.",
    "color":"Gray","colorVi":"Xám",
    "doc":"images\\Freshlook\\5\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":5,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},

    {"id":"f06","brandId":"f",
    "name":"COLORBLENDS GREEN PRESCRIPTION ",
    "pic":"images\\Freshlook\\1\\1.jpg","pic2":"images\\Freshlook\\1\\2.jpg",
    "price":13,
    "detail":"Discover a vibrant new eye color with the Freshlook Colorblends Green  Contact Lenses in 30 Day - a natural everyday design.",
    "detailVi":"Khám phá màu mắt mới đầy sức sống với Kính áp tròng Freshlook Colorblends Green trong 30 ngày - một thiết kế tự nhiên hàng ngày.",
    "color":"Green","colorVi":"Xanh lá",
    "doc":"images\\Freshlook\\1\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":3,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"f07","brandId":"f",
    "name":"COLORBLENDS AMETHYST PRESCRIPTION ",
    "pic":"images\\Freshlook\\2\\1.jpg","pic2":"images\\Freshlook\\2\\2.jpg",
    "price":12,
    "detail":"With the Freshlook Colorblends Amethyst  Contact Lenses in 30 Day, you can enjoy a gorgeous purple tone in a natural design.",
    "detailVi":"Với Kính áp tròng thạch anh tím Freshlook Colorblends trong 30 ngày, bạn có thể tận hưởng tông màu tím tuyệt đẹp trong một thiết kế tự nhiên.",
    "color":"Purple","colorVi":"Tím",
    "doc":"images\\Freshlook\\2\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
    
    {"id":"f08","brandId":"f",
    "name":"COLORBLENDS BLUE PRESCRIPTION ",
    "pic":"images\\Freshlook\\3\\1.jpg","pic2":"images\\Freshlook\\3\\2.jpg",
    "price":11,
    "detail":"Try out a natural new eye colour with the realistic look of the Freshlook Colorblends Blue Coloured Contact Lenses in 30 Day!",
    "detailVi":"Hãy thử màu mắt mới tự nhiên với kiểu dáng thực tế của Kính áp tròng màu xanh Freshlook Colorblends trong 30 ngày!",
    "color":"Blue","colorVi":"Xanh",
    "doc":"images\\Freshlook\\3\\CONTACT-LENSES.docx",
    "brand":"Freshlook",
    "manufacturer":"Fresh look, Alcon",
    "style":"Natural","styleVi":"Thời trang",
    "duration":90,
    "quantity":"2 per pack(pair)","quantityVi":"cặp 2 tròng",
    "corrective_Len":"yes","corrective_LenVi":"có",
    "type":"prescription","typeVi":"kính thuốc",
    "diameter":14.5,
    "base_curve":8.6,
    "water_content":"55%",
    "made_from":"Phemfilcon A",
    "rating":4,
    "comment":"<hr>Superman<br>I love it<hr>Batman<br>I like it<hr>Spiderman<br>Best contact lenese<hr>Master Chief<br>I don't need contact lenese"},
];
var glass_product = [
    {
        //Gucci
    "IDbrand":"g",
    "id":"g01",
    "name_brand":"GUCCI",
    "name":"Moira",
    "img":"img//Gucci//1_gucci.jpg",
    "img1":"img//Gucci//1_gucci.jpg",
    "img2":"img//Gucci//1.1_gucci.jpg",
    "img3":"img//Gucci//1.2_gucci.jpg",
    "img4":"img//Gucci//1.3_gucci.png",
    "imgmodel1":"img//Model//Uvalde1.jpg",
    "imgmodel2":"img//Model//Uvalde2.jpg",
    "price":29.5,
    "color":"Black","colorVi":"Đen",
    "sku":"SUP1040",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Round","shapeVi":"Tròn",
    "weight":"20.5g (0.72 oz)",
    "gender":"Women","genderVi":"Nữ",
    "matertial":"TR90",
    "progressive":"Yes",
    "framewidth":"139 mmm",
    "lenwidth":"50 mm",
    "lenseheight":"45 mm",
    "brigde":"21 mm",
    "diagonal":"50 mm",
    "templelength":"152 mm",
    "description":" The Moira sunglasses bring vintage details and minimalistic influences together to create a cool, casual pair of frames. Throwback touches like the round shaped frame and gradient color have serious retro appeal, while the slim arms and integrated nose pads keep things simple and fresh. Made from TR90, the Moira frames are ultra-lightweight and comfortable, ready to match up with your favourite jeans-and-sneakers combination and head out the door with you!",
    "descriptionVi":"Kính mát Moira kết hợp các chi tiết cổ điển và ảnh hưởng tối giản lại với nhau để tạo ra một cặp gọng kính mát mẻ, giản dị. Những nét chấm phá như khung hình tròn và màu chuyển sắc có sức hút cổ điển nghiêm túc, trong khi cánh tay thon gọn và miếng đệm mũi tích hợp giúp mọi thứ trở nên đơn giản và tươi mới. Được làm từ TR90, gọng Moira siêu nhẹ và thoải mái, sẵn sàng kết hợp với sự kết hợp quần jean và giày thể thao yêu thích của bạn và cùng bạn đi ra khỏi cửa!",
    "linkdetail":"docx//Moira.docx"
    },
    {"IDbrand":"g",
    "id":"g02",
    "name_brand":"GUCCI",
    "name":"Pascagoula",
    "img":"img//Gucci//2_gucci.jpg",
    "img1":"img//Gucci//2_gucci.jpg",
    "img2":"img//Gucci//2.1_gucci.jpg",
    "img3":"img//Gucci//2.2_gucci.jpg",
    "img4":"img//Gucci//2.3_gucci.png",
    "imgmodel1":"img//Model//Huntsville1.jpg",
    "imgmodel2":"img//Model//Huntsville2.jpg",
    "price":30.99,
    "color":"Black Tiger","colorVi":"Đen Da Báo",
    "sku":"SUP1033",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Round","shapeVi":"Tròn",
    "weight":"27g (0.95 oz)",
    "gender":"Women / Men","genderVi":"Nữ | Nam",
    "matertial":"Acetate",
    "progressive":"Yes",
    "framewidth":"142 mm",
    "lenwidth":"46 mm",
    "lenseheight":"41 mm",
    "brigde":"25 mm",
    "diagonal":"46 mm",
    "templelength":"153 mm",
    "description":"Large faces with angled features will enjoy the impactful look of the Pascagoula frame. The round glasses borrow retro elements, like tapered wingtips, for some fun quirkiness. In addition, the angular brow-line makes this a great option for showing off your brows. The light TR90 frame is complete with slim acetate temple armsPlease note, the actual pattern on eyeglasses may vary slightly from the one pictured.",
    "descriptionVi":"Khuôn mặt lớn với các đặc điểm góc cạnh sẽ thích thú với vẻ ngoài ấn tượng của khung Pascagoula. Những chiếc kính tròn vay mượn các yếu tố cổ điển, giống như đầu cánh thuôn nhọn, để tạo ra một số nét kỳ quặc vui nhộn. Ngoài ra, đường chân mày góc cạnh làm cho đây là một lựa chọn tuyệt vời để bạn khoe đôi lông mày của mình. Gọng TR90 nhẹ được hoàn thiện với tay đền bằng axetat mỏng Xin lưu ý, hoa văn thực tế trên kính mắt có thể khác một chút so với trong hình.",
    "linkdetail":"docx//Pascagoula.docx"
    },
    {"IDbrand":"g",
    "id":"g03",
    "name_brand":"GUCCI",
    "name":"Uvalde",
    "img":"img//Gucci//3_gucci.jpg",
    "img1":"img//Gucci//3_gucci.jpg",
    "img2":"img//Gucci//3.1_gucci.jpg",
    "img3":"img//Gucci//3.2_gucci.jpg",
    "img4":"img//Gucci//3.3_gucci.png",
    "imgmodel1":"img//Model//Uvalde1.jpg",
    "imgmodel2":"img//Model//Uvalde2.jpg",
    "price":9.59,
    "color":"Black","colorVi":"Đen",
    "sku":"SUP1074",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Rectangle","shapeVi":"Chữ nhật",
    "weight":"27.4g(0.97 oz)",
    "gender":"Women | Men","genderVi":"Nữ | Nam",
    "matertial":"TR90",
    "progressive":"Yes",
    "framewidth":"143 mm",
    "lenwidth":"54 mm",
    "lenseheight":"42 mm",
    "brigde":"18 mm",
    "diagonal":"55 mm",
    "templelength":"146 mm",
    "description":"Slim, simple, and sophisticated, the Uvalde sunglasses will bring a smart edge to whatever you are wearing today. The TR90 has a modern, rectangular finish, to create a contemporary yet classy silhouette. Minimalistic detailing such as integrated nose pads and silver metal rivets ensure a versatile finish, so it is easy to slip the Uvalde frames and conquer your day.Please note, the actual pattern on eyeglasses may vary slightly from the one pictured.",
    "descriptionVi":"Mỏng, đơn giản và tinh tế, kính râm Uvalde sẽ mang lại vẻ ngoài thông minh cho bất cứ thứ gì bạn đang đeo hôm nay. TR90 có bề mặt hoàn thiện hình chữ nhật, hiện đại, để tạo ra một hình dáng hiện đại nhưng sang trọng. Các chi tiết tối giản như miếng đệm mũi tích hợp và đinh tán kim loại bạc đảm bảo độ hoàn thiện linh hoạt, do đó bạn có thể dễ dàng trượt gọng kính Uvalde và chinh phục ngày hôm nay của mình.",
    "linkdetail":"docx//Uvalde.docx"
    },
    {"IDbrand":"g",
    "id":"g04",
    "name_brand":"GUCCI",
    "name":"Huntsville",
    "img":"img//Gucci//4_gucci.jpg",
    "img1":"img//Gucci//4_gucci.jpg",
    "img2":"img//Gucci//4.1_gucci.jpg",
    "img3":"img//Gucci//4.2_gucci.jpg",
    "img4":"img//Gucci//4.3_gucci.png",
    "imgmodel1":"img//Model//Huntsville1.jpg",
    "imgmodel2":"img//Model//Huntsville2.jpg",
    "price":29.95,
    "color":"Black","colorVi":"Đen",
    "sku":"SUP1077",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Classic Wayframe","shapeVi":"Wayframe Cổ điển",
    "weight":"13.1g (0.46 oz)",
    "gender":"Women | Men","genderVi":"Nữ | Nam",
    "matertial":"Metal",
    "progressive":"Yes",
    "framewidth":"141 mm",
    "lenwidth":"52 mm",
    "lenseheight":"43 mm",
    "brigde":"20 mm",
    "diagonal":"53 mm",
    "templelength":"146 mm",
    "description":"Rose Gold and Black Huntsville evoke the classic form to create a daring pair of sunglasses. Adjustable nose pads and antiallergic temple tips complete the look.",
    "description":"Rose Gold và Black Huntsville gợi lên hình thức cổ điển để tạo nên một cặp kính râm táo bạo. Miếng đệm mũi có thể điều chỉnh và đầu nhọn đền chống dị ứng hoàn thiện vẻ ngoài.",
    "linkdetail":"docx//Huntsville.docx"
    },
    {"IDbrand":"g",
    "id":"g05",
    "name_brand":"GUCCI",
    "name":"Tabitha",
    "img":"img//Gucci//5_gucci.jpg",
    "img1":"img//Gucci//5_gucci.jpg",
    "img2":"img//Gucci//5.1_gucci.jpg",
    "img3":"img//Gucci//5.2_gucci.jpg",
    "img4":"img//Gucci//5.3_gucci.png",
    "imgmodel1":"img//Model//Cynthia1.jpg",
    "imgmodel2":"img//Model//Cynthia2.jpg",
    "price":15.99,
    "color":"Pink","colorVi":"Hồng",
    "sku":"SUP1068",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Rectangle","shapeVi":"Chữ nhật",
    "weight":" 13.1g (0.46 oz) ",
    "gender":"Women","genderVi":"Nữ",
    "matertial":"TR90",
    "progressive":"Yes",
    "framewidth":"135 mm",
    "lenwidth":"53 mm",
    "lenseheight":"36 mm",
    "brigde":"15 mm",
    "diagonal":"51 mm",
    "templelength":"143 mm",
    "description":"It is all about class in these Tabitha sunglasses. The Rectangle shape will add instant retro charm to your ensemble, finishing off your look with pure sophistication. Elegant and effortless, they have a true city-chic vibe. Made from TR90, slide them on for a lightweight and durable fit for your commute, your weekend, or days spent in the sun.",
    "descriptionVi":"Đó là tất cả về đẳng cấp trong những chiếc kính râm Tabitha này. Hình dạng Hình chữ nhật sẽ tăng thêm nét quyến rũ cổ điển ngay lập tức cho bộ quần áo của bạn, hoàn thiện vẻ ngoài của bạn với sự tinh tế thuần khiết. Thanh lịch và dễ dàng, họ có một sự rung cảm thực sự của thành phố sang trọng. Được làm từ TR90, trượt chúng để có trọng lượng nhẹ và bền phù hợp cho việc đi làm, cuối tuần của bạn hoặc những ngày ở dưới ánh nắng mặt trời.",
    "linkdetail":"docx//Tabitha.docx"
    },
    {"IDbrand":"g",
    "id":"g06",
    "name_brand":"GUCCI",
    "name":"Wharton",
    "img":"img//Gucci//6_gucci.jpg",
    "img1":"img//Gucci//6_gucci.jpg",
    "img2":"img//Gucci//6.1_gucci.jpeg",
    "img3":"img//Gucci//6.2_gucci.jpeg",
    "img4":"img//Gucci//6.3_gucci.png",
    "imgmodel1":"img//Model//Cynthia1.jpg",
    "imgmodel2":"img//Model//Cynthia2.jpg",
    "price":10.99,
    "color":"Gold","colorVi":"Vàng",
    "sku":"SUP1105",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Square","shapeVi":"Vuông",
    "weight":"10g (0.35 oz)",
    "gender":"Women","genderVi":"Nữ",
    "matertial":"TR90",
    "progressive":"Yes",
    "framewidth":"140 mm",
    "lenwidth":"52 mm",
    "lenseheight":"45 mm",
    "brigde":"19 mm",
    "diagonal":"55 mm",
    "templelength":"147 mm",
    "description":"Get ready to look and feel like a movie star in the Wharton sunglasses. The medium sized frame lenses have a rectangular edge, to create an instant statement. This effect is balanced out by slim lines and understated detailing, so you can stand out with a sophisticated finish.",
    "descriptionVi":"Hãy sẵn sàng để trông giống như một ngôi sao điện ảnh với kính mát Wharton. Các ống kính gọng cỡ trung bình có một cạnh hình chữ nhật, để tạo ra một tuyên bố tức thì. Hiệu ứng này được cân bằng bởi các đường nét thanh mảnh và các chi tiết tinh tế, vì vậy bạn có thể nổi bật với lớp hoàn thiện tinh xảo.",
    "linkdetail":"docx//Wharton.docx"
    },
    //Calvin_klein
    {"IDbrand":"k",
    "id":"c01",
    "name_brand":"CALVIN KLEIN",
    "name":"Vera",
    "img":"img//Calvin-Klein//1_calvin.jpg",
    "img1":"img//Calvin-Klein//1_calvin.jpg",
    "img2":"img//Calvin-Klein//1.1_calvin.jpg",
    "img3":"img//Calvin-Klein//1.2_calvin.jpg",
    "img4":"img//Calvin-Klein//1.3_calvin.png",
    "imgmodel1":"img//Model//Cynthia1.jpg",
    "imgmodel2":"img//Model//Cynthia2.jpg",
    "price":24.95,
    "color":"Light Gold","colorVi":"Vàng",
    "sku":"SUP1078",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Polygon","shapeVi":"Đa giác",
    "weight":"11g (0.39 oz)",
    "gender":"Women","genderVi":"Nữ",
    "matertial":"Mental",
    "progressive":"Yes",
    "framewidth":"136 mm",
    "lenwidth":"50 mm",
    "lenseheight":"48 mm",
    "brigde":"20 mm",
    "diagonal":"51 mm",
    "templelength":"148 mm",
    "description":"The Vera sunglasses provide an effortless look that will make you the envy of everyone around you. Featuring a sleek metal construction,With adjustable nose pads and heart ornaments decorated temple arm, these thin wire glasses boast a chic design to bring attention to your eyes.",
    "descriptionVi":"Kính mát Vera mang đến một vẻ ngoài dễ dàng khiến bạn phải ghen tị với mọi người xung quanh. Với cấu trúc kim loại bóng bẩy, Với miếng đệm mũi có thể điều chỉnh và đồ trang trí trái tim được trang trí trên cánh tay đền, những chiếc kính dây mỏng này có thiết kế sang trọng để thu hút sự chú ý vào đôi mắt của bạn.",
    "linkdetail":"docx//Vera.docx"
    },
    {"IDbrand":"k",
     "id":"c02",
    "name_brand":"CALVIN KLEIN",
    "name":"Marlowe",
    "img":"img//Calvin-Klein//2_calvin.jpg",
    "img1":"img//Calvin-Klein//2_calvin.jpg",
    "img2":"img//Calvin-Klein//2.1_calvin.jpg",
    "img3":"img//Calvin-Klein//2.2_calvin.jpg",
    "img4":"img//Calvin-Klein//2.3_calvin.png",
    "imgmodel1":"img//Model//Marlowe1.jpg",
    "imgmodel2":"img//Model//Marlowe2.jpg",
    "price":19.95,
    "color":"Gold","colorVi":"Vàng",
    "sku":"SUP0711",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Cat Eye","shapeVi":"Mắt mèo",
    "weight":"13.00g (0.46 oz)",
    "gender":"Women","genderVi":"Nữ",
    "matertial":"Metal",
    "progressive":"Yes",
    "framewidth":"138 mm",
    "lenwidth":"54 mm",
    "lenseheight":"49 mm",
    "brigde":"18 mm",
    "diagonal":"58 mm",
    "templelength":"144 mm",
    "description":"Marlowe's flirty cat-eye shape and pink mirrored lenses are a year-round must have. Featuring adjustable nose pads and metal frame for a lightweight, barely there feel.<br>OUR RECOMMENDATION:<br>We love a good cateye frame on diamond and oval face shapes! Of course, you know yourself best, so if you like them, we're positive you can rock them!",
    "descriptionVi":"Hình dạng mắt mèo quyến rũ của Marlowe và ống kính tráng gương màu hồng là những thứ phải có quanh năm. Có miếng đệm mũi có thể điều chỉnh và khung kim loại cho cảm giác nhẹ, gần như không có.",
    "linkdetail":"docx//Marlowe.docx"
    },
    {"IDbrand":"k",
        "id":"c03",
        "name_brand":"CALVIN KLEIN",
        "name":"Kerlins",
        "img":"img//Calvin-Klein//3_calvin.jpg",
        "img1":"img//Calvin-Klein//3_calvin.jpg",
        "img2":"img//Calvin-Klein//3.1_calvin.jpg",
        "img3":"img//Calvin-Klein//3.2_calvin.jpg",
        "img4":"img//Calvin-Klein//3.3_calvin.png",
        "imgmodel1":"img//Model//Kerlins1.jpg",
        "imgmodel2":"img//Model//Kerlins1.jpg",
        "price":29.95,
        "color":"Black","colorVi":"Đen",
        "sku":"SUP0659",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Cat Eye","shapeVi":"Mắt mèo",
        "weight":"24g (0.85 oz)",
        "gender":"Women","genderVi":"Nữ",
        "matertial":"Acetate",
        "progressive":"Yes",
        "framewidth":"138 mm",
        "lenwidth":"52 mm",
        "lenseheight":"39 mm",
        "brigde":"17 mm",
        "diagonal":"53 mm",
        "templelength":"148 mm",
        "description":"Glassesshop Kerlins cat eye sunglasses are made of durable and refreshingly bright Italian acetate material. Coming with Flora and Black colors, this cat eye designed frame is suitable for most of women. With UV-protect lenses they can be used in prescription sunglasses and fashion sunglasses. It is suitable for all fashion collections.",
        "descriptionVi":"Kính mát mắt mèo của Glassesshop Kerlins được làm từ chất liệu acetate Ý bền và sáng. Với hai màu Flora và Black, gọng kính mắt mèo này phù hợp với hầu hết phụ nữ. Với tròng kính chống tia UV, chúng có thể được sử dụng trong kính râm theo toa và kính râm thời trang. Nó phù hợp với tất cả các bộ sưu tập thời trang.",
        "linkdetail":"docx//Kerlins.docx"
    },
    {"IDbrand":"k",
        "id":"c04",
        "name_brand":"CALVIN KLEIN",
        "name":"Kingston",
        "img":"img//Calvin-Klein//4_calvin.jpg",
        "img1":"img//Calvin-Klein//4_calvin.jpg",
        "img2":"img//Calvin-Klein//4.1_calvin.jpg",
        "img3":"img//Calvin-Klein//4.2_calvin.jpg",
        "img4":"img//Calvin-Klein//4.3_calvin.png",
        "imgBanner":"img//Calvin-Klein-Logo.jpg",
        "imgmodel1":"img//Model//Cynthia1.jpg",
        "imgmodel2":"img//Model//Cynthia2.jpg",
        "price":29.95,
        "color":"Blue","colorVi":"Xanh",
        "sku":"SUP1027",
        "frame":"Full",
        "shape":"Aviator","shapeVi":"Phi công",
        "weight":"27.4g(0.97 oz)",
        "gender":"Women","genderVi":"Nữ",
        "matertial":"Metal | Acetate",
        "progressive":"Yes",
        "framewidth":"142 mm",
        "lenwidth":"52 mm",
        "lenseheight":"43.3 mm",
        "brigde":"18 mm",
        "diagonal":"43 mm",
        "templelength":"145 mm",
        "description":"A timeless and endearing classic, Kingston sunglasses bring back the vintage roots of its celebrated aviators. Light and versatile, these sunglasses work well with any outfit and are universally flattering to large face shapes.",
        "descriptionVi":"Là một kiểu kính cổ điển vượt thời gian và đáng yêu, kính mát Kingston mang lại nguồn gốc cổ điển của những chiếc phi công nổi tiếng của hãng. Nhẹ và linh hoạt, những chiếc kính râm này hoạt động tốt với bất kỳ trang phục nào và phổ biến là phù hợp với hình dạng khuôn mặt lớn.",
        "linkdetail":"docx//Kingston.docx"
    },
    {"IDbrand":"k",
    "id":"c05",
    "name_brand":"CALVIN KLEIN",
    "name":"Marshall",
    "img":"img//Calvin-Klein//5_calvin.jpg",
    "img1":"img//Calvin-Klein//5_calvin.jpg",
    "img2":"img//Calvin-Klein//5.1_calvin.jpg",
    "img3":"img//Calvin-Klein//5.2_calvin.jpg",
    "img4":"img//Calvin-Klein//5.3_calvin.png",
    "imgmodel1":"img//Model//Cynthia1.jpg",
    "imgmodel2":"img//Model//Cynthia2.jpg",
    "price":29.95,
    "color":"Gold Black","colorVi":"Vàng Đen",
    "sku":"SUP0842",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Aviator","shapeVi":"Phi công",
    "weight":"20.6g (0.73 oz)",
    "gender":"Men","genderVi":"Nam",
    "matertial":"Metal",
    "progressive":"Yes",
    "framewidth":"150 mm",
    "lenwidth":"62 mm",
    "lenseheight":"44 mm",
    "brigde":"18 mm",
    "diagonal":"62 mm",
    "templelength":"138 mm",
    "description":"Using classical retro aviator frame design, Marshall Sunglasses are made of new TR90 material. Without complicated decoration, it fits prescription sunglasses and no-prescription sunglasses. Featured with polarized lenses protecting your eyes from the hurt of strong sunlight, adjustable nose pads, double-bridge design, the polished and sophisticated sunglasses are a must have for men.",
    "descriptionVi":"Sử dụng thiết kế gọng phi công cổ điển theo phong cách cổ điển, Kính mát Marshall được làm bằng vật liệu TR90 mới. Không cần trang trí phức tạp, nó phù hợp với kính râm theo toa và kính râm không cần toa. Nổi bật với tròng kính phân cực bảo vệ đôi mắt của bạn khỏi tác hại của ánh nắng mạnh, miếng đệm mũi có thể điều chỉnh, thiết kế hai cầu, chiếc kính râm bóng bẩy và tinh xảo là điều cần có đối với nam giới.",
    "linkdetail":"docx//Marshall.docx"
    },
    {"IDbrand":"k",
    "id":"c06",
    "name_brand":"CALVIN KLEIN",
    "name":"Ely",
    "img":"img//Calvin-Klein//6_calvin.jpg",
    "img1":"img//Calvin-Klein//6_calvin.jpg",
    "img2":"img//Calvin-Klein//6.1_calvin.jpg",
    "img3":"img//Calvin-Klein//6.2_calvin.jpg",
    "img4":"img//Calvin-Klein//6.3_calvin.png",
    "imgmodel1":"img//Model//Uvalde1.jpg",
    "imgmodel2":"img//Model//Uvalde2.jpg",
    "price":29.95,
    "color":"Black","colorVi":"Đen",
    "sku":"SUP0997",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Rectangle","shapeVi":"Chữ nhật",
    "weight":"16.1g (0.57 oz)",
    "gender":"Women | Men","genderVi":"Nữ | Nam",
    "matertial":"TR90",
    "progressive":"Yes",
    "framewidth":"146 mm",
    "lenwidth":"54 mm",
    "lenseheight":"46 mm",
    "brigde":"18 mm",
    "diagonal":"57 mm",
    "templelength":"148 mm",
    "description":"Are you looking for a pair of affordable and chic mirrored sunglasses? Glassesshop offers 4 colors mirrored sunglasses. Add a timeless touch to your look with these mirrored sunglasses, a must have accessory for anyone who likes to make a striking and lasting impression.",
    "descriptionVi":"Bạn đang tìm kiếm một cặp kính râm tráng gương sang trọng và giá cả phải chăng? Eyeconic cung cấp kính râm tráng gương 4 màu. Thêm một nét đẹp vượt thời gian cho vẻ ngoài của bạn với những chiếc kính râm tráng gương này, một phụ kiện phải có cho bất kỳ ai thích tạo ấn tượng nổi bật và lâu dài.",
    "linkdetail":"docx//Ely.docx"
    },
    //Lascote
    {"IDbrand":"l",
    "id":"l01",
    "name_brand":"LACOSTE",
    "name":"Pueblo",
    "img":"img//Lacoste//1_lacoste.jpg",
    "img1":"img//Lacoste//1_lacoste.jpg",
    "img2":"img//Lacoste//1.1_lacoste.jpg",
    "img3":"img//Lacoste//1.2_lacoste.jpg",
    "img4":"img//Lacoste//1.3_lacoste.png",
    "imgmodel1":"img//Model//Pueblo1.jpg",
    "imgmodel2":"img//Model//Pueblo2.jpg",
    "price":19.95,
    "color":"Light","colorVi":"Trắng",
    "sku":"SUP0967",
    "frame":"Full","frameVi":"Đầy",
    "shape":"Cat Eye","shapeVi":"Mắt mèo",
    "weight":"23.2g (0.82 oz)",
    "gender":"Women | Men","genderVi":"Nữ | Nam",
    "matertial":"Metal",
    "progressive":"Yes",
    "framewidth":"149 mm",
    "lenwidth":"57 mm",
    "lenseheight":"45 mm",
    "brigde":"19 mm",
    "diagonal":"54 mm",
    "templelength":"147 mm",
    "description":"Playfully sweet, Pueblo is a delicate cat-eye frame that will beautifully flatter triangle and heart shape faces with adjustable nose pads. The subtle curves on these glasses add softness to sharp facial features. This refined pair provides all-day comfort for large to oversized faces.",
    "descriptionVi":"Ngọt ngào tinh nghịch, Pueblo là một gọng kính mắt mèo tinh tế sẽ làm phẳng đẹp khuôn mặt hình tam giác và hình trái tim với miếng đệm mũi có thể điều chỉnh. Những đường cong tinh tế trên cặp kính này tạo thêm sự mềm mại cho các đường nét trên khuôn mặt sắc nét. Đôi tinh tế này mang lại sự thoải mái cả ngày cho những khuôn mặt từ lớn đến quá khổ.",
    "linkdetail":"docx//Pueblo.docx"
    },
    {"IDbrand":"l",
        "id":"l02",
        "name_brand":"LACOSTE",
        "name":"Cynthia",
        "img":"img//Lacoste//2_lacoste.jpg",
        "img1":"img//Lacoste//2_lacoste.jpg",
        "img2":"img//Lacoste//2.1_lacoste.jpg",
       "img3":"img//Lacoste//2.2_lacoste.jpg",
       "img4":"img//Lacoste//2.3_lacoste.png",
       "imgmodel1":"img//Model//Cynthia1.jpg",
        "imgmodel2":"img//Model//Cynthia2.jpg",
        "price":30,
        "color":"Gold","colorVi":"Vàng",
        "sku":"FM1481",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Oval","shapeVi":"Hình trái xoan",
        "weight":"10.6g (0.37 oz)",
        "gender":"Women","genderVi":"Nữ | Nam",
        "matertial":"Metal",
        "progressive":"Yes",
        "framewidth":"130 mm",
        "lenwidth":"47 mm",
        "lenseheight":"36 mm",
        "brigde":"21 mm",
        "diagonal":"45 mm",
        "templelength":"140 mm",
        "description":"These finely oval metal frames with water-waved detail are instantly elevating, whatever your wardrobe mood. The curved bridge, adjustable nose pads, and acetate-tipped slimline arms offer a comfortable, adjustable fit.",
        "descriptionVi":"Những khung kim loại hình bầu dục tinh xảo với chi tiết sóng nước này sẽ ngay lập tức nâng tầm, bất kể tâm trạng tủ quần áo của bạn. Sống mũi cong, miếng đệm mũi có thể điều chỉnh và cánh tay thon gọn được bọc bằng axetat mang lại cảm giác thoải mái, vừa vặn có thể điều chỉnh.",
        "linkdetail":"docx//Cynthia.docx"
     },
     {"IDbrand":"l",
        "id":"l03",
        "name_brand":"LACOSTE",
        "name":"BowlingGreen",
        "img":"img//Lacoste//3_lacoste.jpg",
        "img1":"img//Lacoste//3_lacoste.jpg",
        "img2":"img//Lacoste//3.1_lacoste.jpg",
       "img3":"img//Lacoste//3.2_lacoste.jpg",
       "img4":"img//Lacoste//3.3_lacoste.png",
       "imgmodel1":"img//Model//BowlingGreen1.jpg",
       "imgmodel2":"img//Model//BowlingGreen2.jpg",
        "price":29.95,
        "color":"Black","colorVi":"Đen",
        "sku":"FP0917",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Rectangle","shapeVi":"Chữ nhật",
        "weight":" 11g (0.39 oz)",
        "gender":"Women | Men","genderVi":"Nữ | Nam",
        "matertial":"TR90 | Acetate",
        "progressive":"Yes",
        "framewidth":"140 mm",
        "lenwidth":"54 mm",
        "lenseheight":"36 mm",
        "brigde":"16 mm",
        "diagonal":"55 mm",
        "templelength":"147 mm",
        "description":"BowlingGreen Rectangle eyeglasses is crafted from lightweight and  comfortable TR-90, fit for both men and women. Tortoise, Black, Black/Brown and Black/Blue colors are available in this type of eyewear. Besides, this pair of full rectangle is a great choice for those who need large glasses or who have strong prescription and rectangular shaped lenses suit most faces. ",
        "descriptionVi":"Kính mắt hình chữ nhật BowlingGreen được chế tác từ TR-90 nhẹ và thoải mái, phù hợp cho cả nam và nữ. Các màu Rùa, Đen, Đen / Nâu và Đen / Xanh dương có sẵn trong loại kính mắt này. Bên cạnh đó, cặp kính hình chữ nhật đầy đủ này là sự lựa chọn tuyệt vời cho những ai cần kính lớn hoặc những người có kính cường lực và tròng kính hình chữ nhật phù hợp với hầu hết các khuôn mặt.",
        "linkdetail":"docx//BowlingGreen.docx"
        },
        {"IDbrand":"l",
            "id":"l04",
            "name_brand":"LACOSTE",
            "name":"Bruno",
            "img":"img//Lacoste//4_lacoste.jpg",
            "img1":"img//Lacoste//4_lacoste.jpg",
            "img2":"img//Lacoste//4.1_lacoste.jpg",
            "img3":"img//Lacoste//4.2_lacoste.jpg",
            "img4":"img//Lacoste//4.3_lacoste.png",
            "imgmodel1":"img//Model//Bruno1.jpg",
            "imgmodel2":"img//Model//Bruno2.jpg",
            "price":19.95,
            "color":"Black","colorVi":"Đen",
            "sku":"FP1508",
            "frame":"Full","frameVi":"Đầy",
            "shape":"Rectangle","shapeVi":"Chữ nhật",
            "weight":"10g (0.35 oz)",
            "gender":"Men","genderVi":"Nam",
            "matertial":"TR90",
            "progressive":"Yes",
            "framewidth":"140 mm",
            "lenwidth":"55 mm",
            "lenseheight":"39 mm",
            "brigde":"16 mm",
            "diagonal":"57 mm",
            "templelength":"148 mm",
            "description":"Bruno eyeglasses are made of flexible and lightweight TR90 material, four color options: Black/Gunmetal, Black/Brown, Black/Blue and solid Black. Featured with concise and comfortable wayframe design, this frame is a great choice for most of men who are looking for a pair of stylish, comfortable and affordable eyeglasses. Computer eyeglasses and reading eyeglasses both are available. ",
            "descriptionVi":"Kính mắt Bruno được làm từ chất liệu TR90 dẻo và nhẹ, bốn màu tùy chọn: Đen / Gunmetal, Đen / Nâu, Đen / Xanh và Đen đặc. Nổi bật với thiết kế kiểu dáng ngắn gọn và thoải mái, gọng kính này là sự lựa chọn tuyệt vời cho hầu hết những người đàn ông đang tìm kiếm một cặp kính mắt thời trang, thoải mái và giá cả phải chăng. Cả kính đeo mắt máy tính và kính mắt đọc sách đều có sẵn.",
            "linkdetail":"docx//Bruno.docx"
        },
        {"IDbrand":"l",
            "id":"l05",
            "name_brand":"LACOSTE",
            "name":"Brunswick",
            "img":"img//Lacoste//5_lacoste.jpg",
            "img1":"img//Lacoste//5_lacoste.jpg",
            "img2":"img//Lacoste//5.1_lacoste.jpg",
            "img3":"img//Lacoste//5.2_lacoste.jpg",
            "img4":"img//Lacoste//5.3_lacoste.png",
            "imgmodel1":"img//Model//Brunswick1.jpg",
             "imgmodel2":"img//Model//Brunswick2.jpg",
            "price":29.95,
            "color":"Black Tiger","colorVi":"Đen Da Báo",
            "sku":"FM1017",
            "frame":"Full","frameVi":"Đầy",
            "shape":"Round","shapeVi":"Tròn",
            "weight":"13g (0.46 oz)",
            "gender":"Women | Men","genderVi":"Nữ | Nam",
            "matertial":"Mental",
            "progressive":"Yes",
            "framewidth":"135 mm",
            "lenwidth":"50 mm",
            "lenseheight":"50 mm",
            "brigde":"18 mm",
            "diagonal":"50 mm",
            "templelength":"135 mm",
            "description":"Brunswick eyeglasses provide a classic rounded frame in a solid black tone. Crafted from high-quality metal materials, the Brunswick features adjustble nose pads and a thin build, resulting in a barely there feel and increased comfort. Perfect for the quirky individual and for any occasion. <br><br>OUR RECOMMENDATION:<br>Rounded eyewear looks great on square shaped faces. The softness of the frame complements and balances sharp features for a winning look. Of course, you know yourself best, so if you like them, we're sure you can rock them!",
            "descriptionVi":"Kính mắt Brunswick có gọng tròn cổ điển với tông màu đen đồng nhất. Được chế tác từ vật liệu kim loại chất lượng cao, Brunswick có đệm mũi có thể điều chỉnh và kết cấu mỏng, mang lại cảm giác vừa vặn và tăng độ thoải mái. Hoàn hảo cho những người kỳ quặc và cho bất kỳ dịp nào.",
            "linkdetail":"docx//Brunswick.docx"
        },
        {"IDbrand":"l",
            "id":"l06",
            "name_brand":"LASCOTE",
            "name":"Newman",
            "img":"img//Lacoste//6_lacoste.jpg",
            "img1":"img//Lacoste//6_lacoste.jpg",
            "img2":"img//Lacoste//6.1_lacoste.jpg",
            "img3":"img//Lacoste//6.2_lacoste.jpg",
            "img4":"img//Lacoste//6.3_lacoste.png",
            "imgmodel1":"img//Model//Bruno1.jpg",
            "imgmodel2":"img//Model//Bruno2.jpg",
            "price":19.95,
            "color":"Black","colorVi":"Đen",
            "sku":"SUP0908",
            "frame":"Full","frameVi":"Đầy",
            "shape":"Round","shapeVi":"Tròn",
            "weight":" 9.7g (0.34 oz)",
            "gender":"Women | Men","genderVi":"Nữ | Nam",
            "matertial":"TR90 | Acetate",
            "progressive":"Yes",
            "framewidth":"142 mm",
            "lenwidth":"52 mm",
            "lenseheight":"43.3 mm",
            "brigde":"18 mm",
            "diagonal":"43 mm",
            "templelength":"145 mm",
            "description":"Newman Round sunglasses are made of lightweight material TR90. We provide three colors: light Gray, Champagne and Black. Featured with key-hole nose bridge design, they are very suitable for men or women who are looking a pair of comfortable and affordable sunglasses.",
            "descriptionVi":"Kính râm Newman Round được làm bằng vật liệu nhẹ TR90. Chúng tôi cung cấp ba màu: Xám nhạt, Sâm panh và Đen. Nổi bật với thiết kế sống mũi có lỗ khóa, chúng rất thích hợp cho các bạn nam hay nữ đang tìm kiếm một cặp kính râm vừa ý và hợp túi tiền.",
            "linkdetail":"docx//Newman.docx"
        },
        //Nike
        {"IDbrand":"n",
        "id":"n01",
        "name_brand":"NIKE",
        "name":"Nodia",
        "img":"img//Nike//1_nike.jpg",
        "img1":"img//Nike//1_nike.jpg",
        "img2":"img//Nike//1.1_nike.jpg",
        "img3":"img//Nike//1.2_nike.jpg",
        "img4":"img//Nike//1.3_nike.png",
        "imgmodel1":"img//Model//Nodia1.jpg",
        "imgmodel2":"img//Model//Nodia2.jpg",
        "price":29.99,
        "color":"Black","colorVi":"Đen",
        "sku":"SUP0700",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Rectangle","shapeVi":"Chữ nhật",
        "weight":"27.4g(0.97 oz)",
        "gender":"Men","genderVi":"Nam",
        "matertial":"Acetate",
        "progressive":"Yes",
        "framewidth":"142 mm",
        "lenwidth":"52 mm",
        "lenseheight":"43.3 mm",
        "brigde":"18 mm",
        "diagonal":"43 mm",
        "templelength":"145 mm",
        "description":"The Nike Hyper force Elite sunglasses have the Nike Elite one-piece lens for superior coverage and clarity. The Nike + Zeiss Optics provide extraordinary clarity and perception. Ventilated, self-adjusting nose bridge provides an individualized fit. Super-lightweight, aerodynamic combined lens-frame reduces wind resistance. Rubber channels in temple arms increase airflow and grip. Ventilated temple arms prevent fogging and moisture accumulation. Frame accommodates Interchange lenses for any light conditions. Secondary lens included. Nike Vision tints are scientifically tuned for specific environments. Using light transmission analysis, optimization of colors and light levels are dynamically filtered through each lens. This light architecture allows the creation of lenses with the perfect vision profile for sport, and environment.",
        "descriptionVi":"Kính râm Nike Hyper force Elite có thấu kính một mảnh Nike Elite cho độ bao phủ và độ rõ nét vượt trội. Quang học Nike + Zeiss cung cấp độ rõ nét và cảm nhận phi thường. Sống mũi thông thoáng, tự điều chỉnh mang đến sự phù hợp với từng cá nhân. Khung thấu kính kết hợp khí động học, siêu nhẹ giúp giảm sức cản của gió. Các rãnh cao su trong cánh tay đền giúp tăng luồng không khí và độ bám. Các cánh tay đền thông thoáng ngăn chặn sương mù và tích tụ hơi ẩm. Khung có thể chứa thấu kính Interchange cho mọi điều kiện ánh sáng. Ống kính phụ bao gồm. Màu sắc của Nike Vision được điều chỉnh một cách khoa học cho các môi trường cụ thể. Sử dụng phân tích truyền ánh sáng, tối ưu hóa màu sắc và mức độ ánh sáng được lọc động qua mỗi ống kính. Kiến trúc ánh sáng này cho phép tạo ra các thấu kính có cấu hình thị lực hoàn hảo cho thể thao và môi trường.",
        "linkdetail":"docx//Nodia.docx"
    },
    {"IDbrand":"n",
        "id":"n02",
        "name_brand":"NIKE",
        "name":"Christian",
        "img":"img//Nike//2_nike.jpg",
        "img1":"img//Nike//2_nike.jpg",
        "img2":"img//Nike//2.1_nike.jpg",
        "img3":"img//Nike//2.2_nike.jpg",
        "img4":"img//Nike//2.3_nike.png",
        "imgmodel1":"img//Model//Christian1.jpg",
        "imgmodel2":"img//Model//Christian2.jpg",
        "price":29.95,
        "color":"Black","colorVi":"Đen",
        "sku":"SUP0759",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Rectangle","shapeVi":"Chữ nhật",
        "weight":" 20.7g (0.73 oz)",
        "gender":"Men","genderVi":"Nam",
        "matertial":"TR90",
        "progressive":"Yes",
        "framewidth":"145 mm",
        "lenwidth":"61 mm",
        "lenseheight":"39 mm",
        "brigde":"17 mm",
        "diagonal":"62 mm",
        "templelength":"135 mm",
        "description":"It is all about class in these Joa sunglasses. The large-sized cat-eye shape will add instant retro charm to your ensemble, finishing off your look with pure sophistication. Elegant and effortless, they have a true city-chic vibe. Made from TR90, slide them on for a lightweight and durable fit for your commute, your weekend, or days spent in the sun.",
        "descriptionVi":"Đó là tất cả về đẳng cấp trong những chiếc kính râm Joa này. Hình dạng mắt mèo cỡ lớn sẽ tăng thêm nét quyến rũ cổ điển ngay lập tức cho bộ trang phục của bạn, hoàn thiện vẻ ngoài của bạn với sự tinh tế thuần khiết. Thanh lịch và dễ dàng, họ có một sự rung cảm thực sự của thành phố sang trọng. Được làm từ TR90, trượt chúng để có trọng lượng nhẹ và bền phù hợp cho việc đi làm, cuối tuần của bạn hoặc những ngày ở dưới ánh nắng mặt trời.",
        "linkdetail":"docx//Christian.docx"
    },
    {"IDbrand":"n",
        "id":"n03",
        "name_brand":"NIKE",
        "name":"Elroy",
        "img":"img//Nike//3_nike.jpg",
        "img1":"img//Nike//3_nike.jpg",
        "img2":"img//Nike//3.1_nike.jpg",
        "img3":"img//Nike//3.2_nike.jpg",
        "img4":"img//Nike//3.3_nike.png",
        "imgmodel1":"img//Model//Elroy1.jpg",
        "imgmodel2":"img//Model//Elroy2.jpg",
        "price":29.95,
        "color":"Black","colorVi":"Đen",
        "sku":"SUP1014",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Rectangle","shapeVi":"Chữ nhật",
        "weight":"27.4g(0.97 oz)",
        "gender":"Men","genderVi":"Nam",
        "matertial":"TR90",
        "progressive":"Yes",
        "framewidth":"145 mm",
        "lenwidth":"61 mm",
        "lenseheight":"39 mm",
        "brigde":"17 mm",
        "diagonal":"62 mm",
        "templelength":"135 mm",
        "description":"Are you looking for a pair of affordable and chic mirrored sunglasses? Glassesshop offers 4 colors mirrored sunglasses. Add a timeless touch to your look with these mirrored sunglasses, a must have accessory for anyone who likes to make a striking and lasting impression.",
        "descriptionVi":"Bạn đang tìm kiếm một cặp kính râm tráng gương sang trọng và giá cả phải chăng? Eyeconic cung cấp kính râm tráng gương 4 màu. Thêm một nét đẹp vượt thời gian cho vẻ ngoài của bạn với những chiếc kính râm tráng gương này, một phụ kiện phải có cho bất kỳ ai thích tạo ấn tượng nổi bật và lâu dài.",
        "linkdetail":"docx//Elroy.docx"
     },
      {"IDbrand":"n",
        "id":"n04",
        "name_brand":"NIKE",
        "name":"Donald",
        "img":"img//Nike//4_nike.jpg",
        "img1":"img//Nike//4_nike.jpg",
        "img2":"img//Nike//4.1_nike.jpg",
        "img3":"img//Nike//4.2_nike.jpg",
        "img4":"img//Nike//4.3_nike.png",
        "imgmodel1":"img//Model//Elroy1.jpg",
        "imgmodel2":"img//Model//Elroy2.jpg",
        "price":19.99,
        "color":"Black","colorVi":"Đen",
        "sku":"SUP1037",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Aviator","shapeVi":"Phi công",
        "weight":"27.4g(0.97 oz)",
        "gender":"Men","genderVi":"Nam",
        "matertial":"Metal",
        "progressive":"Yes",
        "framewidth":"142 mm",
        "lenwidth":"52 mm",
        "lenseheight":"43.3 mm",
        "brigde":"18 mm",
        "diagonal":"43 mm",
        "templelength":"145 mm",
        "description":"Donald Aviator sunglasses are made from polished metal material, featured with polarized lenses and acetate temple arms, adjustable nose pads, double-bridge design, the polished and sophisticated sunglasses are a must have for men. The polarized lenses will protect your eyes from the hurt of strong sunlight. They can be used in prescription sunglasses.",
        "descriptionVi":"Kính mát Donald Aviator được làm từ chất liệu kim loại bóng, nổi bật với tròng kính phân cực và tay đền acetate, miếng đệm mũi có thể điều chỉnh, thiết kế hai cầu, chiếc kính râm bóng bẩy và tinh xảo là điều cần có đối với nam giới. Tròng kính phân cực sẽ bảo vệ đôi mắt của bạn khỏi tác hại của ánh nắng mạnh. Chúng có thể được sử dụng trong kính râm theo toa.",
        "linkdetail":"docx//Donald.docx"
    },
    {"IDbrand":"n",
        "id":"n05",
        "name_brand":"NIKE",
        "name":"Spender",
        "img":"img//Nike//5_nike.jpg",
        "img1":"img//Nike//5_nike.jpg",
        "img2":"img//Nike//5.1_nike.jpg",
        "img3":"img//Nike//5.2_nike.jpg",
        "img4":"img//Nike//5.3_nike.png",
        "imgmodel1":"img//Model//Cynthia1.jpg",
        "imgmodel2":"img//Model//Cynthia2.jpg",
        "price":19.95,
        "color":"White","colorVi":"Trắng",
        "sku":"SUP0632",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Square","shapeVi":"Vuông",
        "weight":"27.4g(0.97 oz)",
        "gender":"Women | Men","genderVi":"Nữ | Nam",
        "matertial":"TR90",
        "progressive":"Yes",
        "framewidth":"152 mm",
        "lenwidth":"56 mm",
        "lenseheight":"43.3 mm",
        "brigde":"18 mm",
        "diagonal":"59 mm",
        "templelength":"150 mm",
        "description":"Spender by Eyeconic features a large square frame available in two colors. A great unisex option that offers simple and stylish comfort for everyday wear.<br>OUR RECOMMENDATION:<br>Square shaped frames look great a round-shaped face. This shape adds defnition while sharper lines complement softer facial features. Square eyewear also provides a slimming effect! ",
        "description":"Spender by Eyeconic có khung hình vuông lớn có hai màu. Một lựa chọn unisex tuyệt vời mang lại sự thoải mái đơn giản và phong cách cho trang phục hàng ngày.",
        "linkdetail":"docx//Spender.docx"
    },
    {"IDbrand":"n",
        "id":"n06",
        "name_brand":"NIKE",
        "name":"Albany",
        "img":"img//Nike//6_nike.jpg",
        "img1":"img//Nike//6_nike.jpg",
        "img2":"img//Nike//6.1_nike.jpg",
        "img3":"img//Nike//6.2_nike.jpg",
        "img4":"img//Nike//6.3_nike.png",
        "imgmodel1":"img//Model//Elroy1.jpg",
        "imgmodel2":"img//Model//Elroy2.jpg",
        "price":29.95,
        "color":"Black","colorVi":"Đen",
        "sku":"SUP1017",
        "frame":"Full","frameVi":"Đầy",
        "shape":"Rectangle","shapeVi":"Chữ nhật",
        "weight":"18.3g (0.65 oz)",
        "gender":"Women | Men","genderVi":"Nữ | Nam",
        "matertial":"TR90",
        "progressive":"Yes",
        "framewidth":"142 mm",
        "lenwidth":"52 mm",
        "lenseheight":"43.3 mm",
        "brigde":"18 mm",
        "diagonal":"43 mm",
        "templelength":"145 mm",
        "description":"The Albany sunglasses bring an instant contemporary edge to whatever you are wearing, thanks to the oversized rectangular frames and simple, clean lines. Integrated nose pads and slim TR90 arms cut a modern silhouette that still has a classic appeal, making them a great choice for daily wear.",
        "descriptionVi":"Kính râm Albany mang đến vẻ hiện đại tức thì cho bất cứ thứ gì bạn đang đeo, nhờ gọng kính hình chữ nhật quá khổ và những đường nét đơn giản, gọn gàng. Các miếng đệm mũi tích hợp và cánh tay TR90 thon gọn cắt một hình bóng hiện đại mà vẫn mang nét cổ điển, khiến chúng trở thành một lựa chọn tuyệt vời cho trang phục hàng ngày.",
        "linkdetail":"docx//Albany.docx"
    },
];

function searchP() {
    var usearch = $("#search").val(); // get value
    var list_productGlass ='';
    var list_productLenses ='';
    var list_product='';
    var patt = /[A-Za-z]/;
    if(patt.test(usearch)){
    for(var v in glass_product){
        if(glass_product[v].name.toLowerCase().search(usearch.toLowerCase()) != -1 || glass_product[v].color.toLowerCase().search(usearch.toLowerCase()) != -1){
            list_productGlass += '<div class="col-xs-12 col-md-4 product">'+
            '     <a href="glass_product.html?key1='+glass_product[v].id+'"><img src="'+glass_product[v].img+'" alt="" style="width:50%;padding:10px;display:block;margin:auto;border-radius:50%"></a>\n'+
            '     <div class="name_produc">'+glass_product[v].name+'</div>\n'+
            '     <div class="price_product">'+"Price: $"+glass_product[v].price+'</div>\n'+
            '     <div class="name_produc"><span style="font-size: 30px;color:'+glass_product[v].color+';"> Color: '+glass_product[v].color+'</span></div>\n'+
            '     </div>';
        }
    }
    list_product+=list_productGlass;
    for(var v in product_json){
        if(product_json[v].name.toLowerCase().search(usearch.toLowerCase()) != -1 || product_json[v].color.toLowerCase().search(usearch.toLowerCase()) != -1){
            list_productLenses += '<div class="col-xs-12 col-md-4 product">'+
            '     <a href="product_detail_page.html?key1='+product_json[v].id+'"><img src="'+product_json[v].pic+'" alt="" style="width:50%;padding:10px;display:block;margin:auto;border-radius:50%"></a>\n'+
            '     <div class="name_produc">'+product_json[v].name+'</div>\n'+
            '     <div class="price_product">'+"Price: $"+product_json[v].price+'</div>\n'+
            '     <div class="name_produc"><span style="font-size: 30px;color:'+product_json[v].color+';"> Color: '+product_json[v].color+'</span></div>\n'+
            '     </div>';
        }
    }
    list_product+=list_productLenses;
    if(list_product == "")
        {
            alert('Can\'t Find Product You Need');
            return 0;
        }
    }
    else{
        alert('Can\'t Find Product You Need');
        return 1;
    }
    $("#searchProduct").html(list_product);
}

    var clearSearch = function()
    {
        list_product = '';
        $("#searchProduct").html(list_product);
    }